[project]
name = "fastapi-tf-rest"
version = "1.0.0"
description = "REST API image classifier"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ai-edge-litert>=1.2.0",
    "opencv-python==4.11.0.86",
    "fastapi[standard]>=0.115.8",
]
